/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appasadosumanabd.ui;

import appasadosumanadb.db.Conexion;
import appasadosumanadb.db.SqlClass;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.util.LinkedList;
import javax.swing.ImageIcon;

/**
 *
 * @author osmel
 */
public class Ventas extends javax.swing.JDialog {

    /**
     * Creates new form Ventas
     */
    public Ventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/logo/Logo_500x500.png")).getImage());
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
        totalesVenta();
    }

    private int x, y;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTopBar = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jLabelLogotipo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMoverVentana = new javax.swing.JLabel();
        jPanelbar1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDia = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jTextFieldMes = new javax.swing.JTextField();
        jLabelID1 = new javax.swing.JLabel();
        jTextFieldAnyio = new javax.swing.JTextField();
        jLabelID2 = new javax.swing.JLabel();
        jLabelID3 = new javax.swing.JLabel();
        jLabelID4 = new javax.swing.JLabel();
        jLabelID5 = new javax.swing.JLabel();
        jLabelID6 = new javax.swing.JLabel();
        jLabelID7 = new javax.swing.JLabel();
        jLabelID8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(34, 34, 34));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopBar.setBackground(new java.awt.Color(255, 101, 0));
        jPanelTopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appasadosumanabd/img/close_icon.png"))); // NOI18N
        jButtonExit.setFocusPainted(false);
        jButtonExit.setFocusable(false);
        jButtonExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/appasadosumanabd/img/close_icon.png"))); // NOI18N
        jButtonExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/appasadosumanabd/img/close_icon_1.png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanelTopBar.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 20, 20));

        jLabelLogotipo.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabelLogotipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appasadosumanabd/img/Logo 50x50.png"))); // NOI18N
        jLabelLogotipo.setText("<html>Asados Umañana<html>");
        jPanelTopBar.add(jLabelLogotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 60));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanelTopBar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 20, 60));

        jMoverVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMoverVentanaMouseDragged(evt);
            }
        });
        jMoverVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMoverVentanaMousePressed(evt);
            }
        });
        jPanelTopBar.add(jMoverVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 60));

        jPanel1.add(jPanelTopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 60));

        jPanelbar1.setBackground(new java.awt.Color(255, 101, 0));
        jPanelbar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanelbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 360, 30));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total de ventas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 20));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 101, 0));
        jLabel2.setText("ASADOS UMAÑA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jTextFieldDia.setEditable(false);
        jTextFieldDia.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextFieldDia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 101, 0)));
        jTextFieldDia.setSelectionColor(new java.awt.Color(255, 101, 0));
        jPanel1.add(jTextFieldDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, 40));

        jLabelID.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 101, 0));
        jLabelID.setText("$");
        jPanel1.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 40));

        jTextFieldMes.setEditable(false);
        jTextFieldMes.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextFieldMes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 101, 0)));
        jTextFieldMes.setSelectionColor(new java.awt.Color(255, 101, 0));
        jPanel1.add(jTextFieldMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 240, 40));

        jLabelID1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID1.setText("Mes");
        jPanel1.add(jLabelID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 20));

        jTextFieldAnyio.setEditable(false);
        jTextFieldAnyio.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextFieldAnyio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 101, 0)));
        jTextFieldAnyio.setSelectionColor(new java.awt.Color(255, 101, 0));
        jPanel1.add(jTextFieldAnyio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 240, 40));

        jLabelID2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID2.setText("Año");
        jPanel1.add(jLabelID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 80, 20));

        jLabelID3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID3.setText("Día");
        jPanel1.add(jLabelID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 80, 20));

        jLabelID4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID4.setForeground(new java.awt.Color(255, 101, 0));
        jLabelID4.setText("COP");
        jPanel1.add(jLabelID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 40));

        jLabelID5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID5.setForeground(new java.awt.Color(255, 101, 0));
        jLabelID5.setText("$");
        jPanel1.add(jLabelID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 40));

        jLabelID6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID6.setForeground(new java.awt.Color(255, 101, 0));
        jLabelID6.setText("$");
        jPanel1.add(jLabelID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 40));

        jLabelID7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID7.setForeground(new java.awt.Color(255, 101, 0));
        jLabelID7.setText("COP");
        jPanel1.add(jLabelID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 40));

        jLabelID8.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabelID8.setForeground(new java.awt.Color(255, 101, 0));
        jLabelID8.setText("COP");
        jPanel1.add(jLabelID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void totalesVenta() {
        try {
            Connection con = Conexion.getConnection();
            CallableStatement cst = null;
            String sql = "{call totalventas(?,?,?)}";
            try {
                cst = con.prepareCall(sql);
                cst.registerOutParameter(1, java.sql.Types.VARCHAR);
                cst.registerOutParameter(2, java.sql.Types.VARCHAR);
                cst.registerOutParameter(3, java.sql.Types.VARCHAR);
                cst.execute();
                jTextFieldDia.setText(cst.getString(1));
                jTextFieldMes.setText(cst.getString(2));
                jTextFieldAnyio.setText(cst.getString(3));
                cst.close();
                con.close();
            } catch (Exception e) {
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jMoverVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMoverVentanaMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jMoverVentanaMouseDragged

    private void jMoverVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMoverVentanaMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jMoverVentanaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventas dialog = new Ventas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelID2;
    private javax.swing.JLabel jLabelID3;
    private javax.swing.JLabel jLabelID4;
    private javax.swing.JLabel jLabelID5;
    private javax.swing.JLabel jLabelID6;
    private javax.swing.JLabel jLabelID7;
    private javax.swing.JLabel jLabelID8;
    public javax.swing.JLabel jLabelLogotipo;
    private javax.swing.JLabel jMoverVentana;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelTopBar;
    public javax.swing.JPanel jPanelbar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAnyio;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldMes;
    // End of variables declaration//GEN-END:variables
}
